Feature/WAL-679
Sphereon-Opensource/ssi-mobile-wallet pull request #175
Opened 2023-12-17 22:02 UTC by BtencateSphereon

2023-12-18 15:01 UTC, nklomp requested changes
Wait for ui components build and 1 remark about some commented code

2023-12-18 15:01 UTC, nklomp commented on src/styles/colors.ts
> +// type Background = 'primaryDark' | 'secondaryDark' | 'primaryLight' | 'secondaryLight';
Remove commented code here and below

2023-12-18 21:58 UTC, BtencateSphereon commented on src/styles/colors.ts
> +// type Background = 'primaryDark' | 'secondaryDark' | 'primaryLight' | 'secondaryLight';
removed

2023-12-19 14:12 UTC, nklomp approved these changes
Lgtm

2023-12-19 14:30 UTC, merged