altered the code to use new interfaces/methods from openid4vci client & common module
Sphereon-Opensource/ssi-mobile-wallet pull request #75
Opened 2023-04-20 14:29 UTC by sksadjad

changes:
- using the new interfaces imported from newly introduced `openid4vci-common` module
- some changes in naming conventions

2023-04-20 15:02 UTC, nklomp requested changes
Missing package.json update and also some small console.log lines which can go or moved to debug as it works now

2023-04-20 15:02 UTC, nklomp commented on src/providers/credential/OpenId4VcIssuanceProvider.ts
> +    console.log(`in OpenId4VcIssuanceProvider.getCredential issuanceOpts: ${JSON.stringify(issuanceOpts)}`)
```suggestion
```

2023-04-20 15:02 UTC, nklomp commented on src/providers/credential/OpenId4VcIssuanceProvider.ts
> +      console.log(`credentialResponses: ${JSON.stringify(credentialResponses)}`)
```suggestion
```

2023-04-21 07:37 UTC, sksadjad commented on src/providers/credential/OpenId4VcIssuanceProvider.ts
> +      console.log(`credentialResponses: ${JSON.stringify(credentialResponses)}`)
removed that line

2023-04-21 07:37 UTC, sksadjad commented on src/providers/credential/OpenId4VcIssuanceProvider.ts
> +    console.log(`in OpenId4VcIssuanceProvider.getCredential issuanceOpts: ${JSON.stringify(issuanceOpts)}`)
removed that line

2023-04-21 07:39 UTC, sksadjad commented
removed the console logs that you mentioned. plus found another place with wrong imports

2023-04-21 07:53 UTC, nklomp approved these changes
LGTM

2023-04-21 08:03 UTC, merged